In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## sentences
sent=['the glass of milk',
      'the glass of juice',
      'I am a good guy',
      'I am a good developer',
      'Understand your value',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'I am a good guy',
 'I am a good developer',
 'Understand your value']

In [4]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'I am a good guy',
 'I am a good developer',
 'Understand your value']

In [5]:
## one hot 
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr

[[4618, 6809, 2009, 2890],
 [4618, 6809, 2009, 2594],
 [9713, 1861, 3127, 2826, 9831],
 [9713, 1861, 3127, 2826, 9523],
 [7625, 1367, 9886]]

#### The above means that at this postion, like 2009th position pe 1 hai! That's it! 

In [7]:
## now word embedding
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4618 6809 2009 2890]
 [   0    0    0    0 4618 6809 2009 2594]
 [   0    0    0 9713 1861 3127 2826 9831]
 [   0    0    0 9713 1861 3127 2826 9523]
 [   0    0    0    0    0 7625 1367 9886]]


In [13]:
## feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

/Users/sahil/Desktop/GenAI Krish/Section-14-Simple-RNN-Project/venv/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


array([[ 0.00122106,  0.0179917 ,  0.02263505,  0.01897374,  0.0275604 ,
        -0.04697735,  0.04812774,  0.02997002,  0.00637317,  0.03888566],
       [ 0.00122106,  0.0179917 ,  0.02263505,  0.01897374,  0.0275604 ,
        -0.04697735,  0.04812774,  0.02997002,  0.00637317,  0.03888566],
       [ 0.00122106,  0.0179917 ,  0.02263505,  0.01897374,  0.0275604 ,
        -0.04697735,  0.04812774,  0.02997002,  0.00637317,  0.03888566],
       [ 0.00122106,  0.0179917 ,  0.02263505,  0.01897374,  0.0275604 ,
        -0.04697735,  0.04812774,  0.02997002,  0.00637317,  0.03888566],
       [ 0.00318923, -0.00557824, -0.00754898, -0.0210317 , -0.01427402,
        -0.00476886,  0.02826418,  0.0302794 , -0.03042494, -0.04608852],
       [ 0.0001436 ,  0.01475382, -0.02869703,  0.04023179,  0.0356831 ,
        -0.00297825,  0.00054834, -0.02011589,  0.00542261,  0.01758388],
       [ 0.04819396,  0.02714424,  0.00663855, -0.03680687, -0.03611066,
         0.01526891, -0.04292075,  0.04530555